### ISSUE TITLE
todo: process logging

### ISSUE THREAD

**Issue by aspick** [aspick/totempole#1]
- [ ] collect process stdout
- [ ] write log file
- [ ] enable log commnad
